columns:
  - travelCode : int
  - userCode : int
  - from : category
  - to : category
  - flightType : category
  - price : float
  - time : float
  - distance : float
  - agency : category
  - date : category

numerical_columns:
  - travelCode
  - userCode
  - price
  - time
  - distance

categorical_columns:
  - from
  - to
  - flightType
  - agency
  - date


# day (day name) should be derieved from date
#then date column can be removed 

drop_columns:
  - travelCode
  - userCode
  - date

# for data transformation
oh_columns:
  - from
  - to
  - flightType
  - agency
  - day

scaler_columns:
  - time
  - distance


