columns:
  - travelCode : int
  - userCode : int
  - from : category
  - to : category
  - flightType : category
  - price : float
  - time : float
  - distance : float
  - agency : category
  - date : category

numerical_columns:
  - travelCode
  - userCode
  - price
  - time
  - distance

categorical_columns:
  - from
  - to
  - flightType
  - agency
  - date

# columns to be removed

drop_columns:
  - travelCode
  - userCode

# for data transformation
oh_columns:
  - from
  - to
  - flightType
  - agency
  - day




num_features:
  - no_of_employees
  - prevailing_wage
  - company_age

or_columns:
  - has_job_experience
  - requires_job_training
  - full_time_position
  - education_of_employee



transform_columns:
  - no_of_employees
  - company_age