columns:
  - travelCode : int
  - userCode : int
  - name : category
  - place : category
  - days : int
  - price : float
  - total : float
  - date : category

numerical_columns:
  - travelCode
  - userCode
  - days
  - price
  - total

categorical_columns:
  - name
  - place
  - date 

# columns to be removed

drop_columns:
  - date
  - travelCode
  - userCode

# for data transformation

label_encode_columns:
  - place

min_max_scale_columns:
  - place_encoded
  - price
  - days
  - popularity

