grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: XGBRegressor
    module: xgboost
    params:
      max_depth: 8
      learning_rate: 0.08
      n_estimators: 300
    search_param_grid:
      max_depth:
      - 3
      - 5
      - 7
      learning_rate:
      - 0.01
      - 0.2
      n_estimators:
      - 100
      - 200
      - 500
      subsample:
      - 0.8
      - 1.0

      
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: sqrt
      n_estimators: 3
    search_param_grid:
      max_depth:
      - 10
      - 15
      - 20
      max_features:
      - sqrt
      - log2
      n_estimators:
      - 100
      - 200
      - 300 