columns:
  - code: category
  - company: category
  - name: category
  - gender: category
  - age: int

numerical_columns:
  - code
  - age

categorical_columns:
  - company
  - name
  - gender


drop_columns:
  - code
  - company
  - age


